/* tslint:disable:no-relative-imports */
import './API/GetWork.test'
import './API/GetWorks.test'
import './API/GetWorksByIssuer.test'
import './API/PostFile.test'
import './API/PostWork.test'
import './BlockchainWriter/BlockInfoDAO.test'
import './Helpers/IPFS.test'
import './SecurityHeaders.test'
import './app.test'
