import '../../src/API/Middlewares/RequestValidationMiddleware.test'
import '../../src/canary.test'
import '../../src/API/Middlewares/RequestValidationMiddleware.test.ts'
import '../../src/API/Router.test.ts'
import '../../src/API/WorkController.test.ts'
import '../../src/BlockchainReader/BlockchainReaderService.test.ts'
import '../../src/BlockchainReader/ClaimController.test.ts'
import '../../src/BlockchainWriter/ClaimController.test.ts'
import '../../src/BlockchainWriter/Router.test.ts'
import '../../src/BlockchainWriter/Service.test.ts'
import '../../src/Helpers/Configuration.test'
import '../../src/Helpers/camelCaseToScreamingSnakeCase.test'
import '../../src/Storage/ClaimController.test.ts'
import '../../src/Storage/IPFS.test.ts'
import '../../src/Storage/Router.test.ts'
import '../../src/Storage/Service.test.ts'
import '../../src/View/Router.test.ts'
import '../../src/View/WorkController.test.ts'
import '../../src/Extensions/Array.test.ts'
import '../../src/Extensions/Error.test.ts'
import '../../src/Extensions/Promise.test.ts'
import '../../src/Helpers/Bitcoin.test'
import '../../src/Helpers/FetchError.test.ts'
import '../../src/Helpers/Logging.test.ts'
import '../../src/Helpers/Time.test.ts'


