// All unit test files should be imported here. For example,
// import '../../src/foo.test'
import '../../src/canary.test'
import '../../src/API/Middlewares/RequestValidationMiddleware.test.ts'
import '../../src/API/Router.test.ts'
import '../../src/API/WorkController.test.ts'
import '../../src/BlockchainReader/BlockchainReaderService.test.ts'
import '../../src/BlockchainReader/ClaimController.test.ts'
import '../../src/BlockchainWriter/ClaimController.test.ts'
import '../../src/BlockchainWriter/Router.test.ts'
import '../../src/BlockchainWriter/Service.test.ts'
import '../../src/Storage/ClaimController.test.ts'
import '../../src/Storage/IPFS.test.ts'
import '../../src/Storage/Router.test.ts'
import '../../src/Storage/Service.test.ts'
import '../../src/View/Router.test.ts'
import '../../src/View/WorkController.test.ts'